### ISSUE TITLE
As I user I want to search for images by Date

### ISSUE THREAD

**Issue by rosselton** [NewcastleRSE/british-printed-images#13]
# User story
"As I user I want to search for images by Date "

## Details

Users can search for images by date using a slider. The slider range is from 1540 to 1800. The date selection section includes a 'hold' facility, the intention of this is to retain a result set while the user completes another search. The workings of this are not obvious for new users; an additional section appears at the top of the list of search options with the date range previously selected and the text 'close'. On clicking on the close text, the section highlights in red the same as the other search option headers. It is then possible to click again on the close text and remove the section.

## Acceptance criteria

This functionality needs to be explored further. It also needs to be re-worked so it is more intuitive for users. The slider works well, but the hold function is confusing. Users should be given more explicit guidance on how to use features.

**Comment by AdamMorton1982** [comment]
Hello Becky,

Again, this is unclear. If this is a hold function, then making clearer and more intuitive would be wonderful. I'm not sure that it is though - as noted in response to another Issue, I think it is a filter. I keep trying, but when I hold I can get not further. The 'held' criteria appears at the top of the search section in red, but your only option is to close it; there is no option to click and see a previous search. 

The hold (filter) changes the total number of images selected in the vertical image gallery to the immediate right of the search bar. 

So, if we can have some sort of 'saved' search' function, that would be fantastic. At present, however, I'm not sure there is one. I may be wrong!

**Comment by rosselton** [comment]
Agreed, this is part of search filter functionality. It would be good to allow users to access previously returned datasets, but this should be classed as a new feature and would require a separate issue.

**Comment by rosselton** [comment]
A date slider is available for 'search by producer' and 'search by event' only. Not relevant for subject or person searches.
