### ISSUE TITLE
As a user I want to explore the Resources section

### ISSUE THREAD

**Issue by rosselton** [NewcastleRSE/british-printed-images#15]
# User story
"As a user I want to explore the Resources section "

## Details
The Resources section consists of  sub-sections:

* Techniques
* History
* Genres
* Historiography
* Directories
* References
* Links

Some of these sub-sections also have sub-menus. The Directories section shows listings of Printmakers, plus Publishers and Printsellers. These sections include an alphabetical navigation sub-menu where not all letters are selectable, as there is no content under that letter. Each letter listing length is determined by the number of entries.

## Acceptance criteria

The expandable menus work fairly well, but the alphabetical navigation on the sub-menus might be better with a simple pagination system that returns an even numbers of records each time. This should be discussed. The References list is long and could also be handled by pagination. The Links listing is short and could possibly be combined with References.

**Comment by AdamMorton1982** [comment]
Hello Becky,

I've had a look at this. The material contained in the resources section is useful, but it is not easy to search/navigate. As you note, simple pagination would be better. A menu with some of the headings (that then links through to the relevant section) would perhaps be more inviting. 

A couple of thoughts:
1) Could the 'Research' and 'Resources' section be combined? It seems to me that they overlap. Some of the items in the 'Research' section are out of date. 'Recent books', for example, were recent in 2010! The two books in question could be added to the historiography section under 'Resource'.
2) I think re-imagining the 'Resource' section as an area where people go to find useful info about how to work with prints is the best idea. Much of the material in the current site is helpful (different techniques; historiography; lists of catalogues, and so on) but I wonder if it would be useful to think about how it is presented.
3) If we do cull the 'Research' section, could we have the 'Print of the Month' section as a separate part of the site? These are good sections. My sense is that they bring people in to the site and show how prints might be studied.
4) The list of printed books to 1640 is also a good resource. I think presenting it in the resource section would be useful.
5) The links list. I think combining it with references makes sense. Some of the links no longer work: Ashmolean, City of London Library, Sutherland Collection, Victoria & Albert Prints and Books, Welcome.

A front page with simple headings that then click through into more detailed sections makes sense. I wonder if it would be useful for me to prune some of the wordier sections of the 'Resources' section?

**Comment by rosselton** [comment]
I think combining Resources and Research is good solution. Out-of-date of date elements can be removed and excessive sections of text can be reduced. Combine Links into References and remove broken urls.

Print of the Month can be a new section.
